---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - apiservice.yaml
  - deployment.yaml
  - rbac.yaml
  - secrets.yaml
  - service.yaml
  - webhook.yaml