apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rexec-impersonator
rules:
- apiGroups: [""]
  resources: ["users", "groups"]
  verbs: ["impersonate"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["userextras/secret-sauce"]
  verbs: ["impersonate"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rexec-impersonator
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rexec-impersonator
subjects:
- kind: ServiceAccount
  name: rexec-impersonator
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: rexec-impersonator
  apiGroup: rbac.authorization.k8s.io